# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

"""

:Author:  Berk Onat <b.onat@warwick.ac.uk>
:Year:    2017
:Licence: UIUC LICENSE



"""


from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_libpymolfile')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_libpymolfile')
    _libpymolfile = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_libpymolfile', [dirname(__file__)])
        except ImportError:
            import _libpymolfile
            return _libpymolfile
        try:
            _mod = imp.load_module('_libpymolfile', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _libpymolfile = swig_import_helper()
    del swig_import_helper
else:
    import _libpymolfile
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def molfile_plugin_list(maxsize: 'int') -> "PyObject *":
    """molfile_plugin_list(maxsize) -> PyObject *"""
    return _libpymolfile.molfile_plugin_list(maxsize)

def molfile_init() -> "int":
    """molfile_init() -> int"""
    return _libpymolfile.molfile_init()

def molfile_finish() -> "int":
    """molfile_finish() -> int"""
    return _libpymolfile.molfile_finish()

def get_plugin(molcapsule: 'PyObject *', plug_no: 'int') -> "PyObject *":
    """get_plugin(molcapsule, plug_no) -> PyObject *"""
    return _libpymolfile.get_plugin(molcapsule, plug_no)

def molfile_plugin_info(molcapsule: 'PyObject *', plugin_no: 'int') -> "PyObject *":
    """molfile_plugin_info(molcapsule, plugin_no) -> PyObject *"""
    return _libpymolfile.molfile_plugin_info(molcapsule, plugin_no)

def open_file_read(molcapsule: 'PyObject *', fname: 'char *', ftype: 'char *', natoms: 'int') -> "PyObject *":
    """open_file_read(molcapsule, fname, ftype, natoms) -> PyObject *"""
    return _libpymolfile.open_file_read(molcapsule, fname, ftype, natoms)

def close_file_read(molpack: 'PyObject *') -> "PyObject *":
    """close_file_read(molpack) -> PyObject *"""
    return _libpymolfile.close_file_read(molpack)

def read_fill_structure(molpack: 'PyObject *', prototype: 'PyObject *') -> "PyObject *":
    """read_fill_structure(molpack, prototype) -> PyObject *"""
    return _libpymolfile.read_fill_structure(molpack, prototype)

def read_fill_bonds(molpack: 'PyObject *') -> "PyObject *":
    """read_fill_bonds(molpack) -> PyObject *"""
    return _libpymolfile.read_fill_bonds(molpack)

def read_fill_angles(molpack: 'PyObject *') -> "PyObject *":
    """read_fill_angles(molpack) -> PyObject *"""
    return _libpymolfile.read_fill_angles(molpack)

def read_fill_next_timestep(molpack: 'PyObject *') -> "PyObject *":
    """read_fill_next_timestep(molpack) -> PyObject *"""
    return _libpymolfile.read_fill_next_timestep(molpack)

def are_plugins_same(molpack_a: 'PyObject *', molpack_b: 'PyObject *') -> "PyObject *":
    """are_plugins_same(molpack_a, molpack_b) -> PyObject *"""
    return _libpymolfile.are_plugins_same(molpack_a, molpack_b)

def are_filehandles_same(molpack_a: 'PyObject *', molpack_b: 'PyObject *') -> "PyObject *":
    """are_filehandles_same(molpack_a, molpack_b) -> PyObject *"""
    return _libpymolfile.are_filehandles_same(molpack_a, molpack_b)
# This file is compatible with both classic and new-style classes.


